/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "EthereumConfig",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EthereumConfig__factory>;
    getContractFactory(
      name: "SepoliaConfig",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SepoliaConfig__factory>;
    getContractFactory(
      name: "FHE",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHE__factory>;
    getContractFactory(
      name: "IDecryptionOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDecryptionOracle__factory>;
    getContractFactory(
      name: "IKMSVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKMSVerifier__factory>;
    getContractFactory(
      name: "IACL",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IACL__factory>;
    getContractFactory(
      name: "IFHEVMExecutor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFHEVMExecutor__factory>;
    getContractFactory(
      name: "IInputVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IInputVerifier__factory>;
    getContractFactory(
      name: "FHECounter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHECounter__factory>;
    getContractFactory(
      name: "FHEVoting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVoting__factory>;
    getContractFactory(
      name: "FHEVotingLocal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVotingLocal__factory>;
    getContractFactory(
      name: "FHEVotingMinimal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVotingMinimal__factory>;
    getContractFactory(
      name: "FHEVotingMock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVotingMock__factory>;
    getContractFactory(
      name: "FHEVotingSepolia",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEVotingSepolia__factory>;
    getContractFactory(
      name: "ConfidentialVoting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConfidentialVoting__factory>;
    getContractFactory(
      name: "SimpleVoting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SimpleVoting__factory>;

    getContractAt(
      name: "EthereumConfig",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EthereumConfig>;
    getContractAt(
      name: "SepoliaConfig",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SepoliaConfig>;
    getContractAt(
      name: "FHE",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHE>;
    getContractAt(
      name: "IDecryptionOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDecryptionOracle>;
    getContractAt(
      name: "IKMSVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IKMSVerifier>;
    getContractAt(
      name: "IACL",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IACL>;
    getContractAt(
      name: "IFHEVMExecutor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFHEVMExecutor>;
    getContractAt(
      name: "IInputVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IInputVerifier>;
    getContractAt(
      name: "FHECounter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHECounter>;
    getContractAt(
      name: "FHEVoting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVoting>;
    getContractAt(
      name: "FHEVotingLocal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVotingLocal>;
    getContractAt(
      name: "FHEVotingMinimal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVotingMinimal>;
    getContractAt(
      name: "FHEVotingMock",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVotingMock>;
    getContractAt(
      name: "FHEVotingSepolia",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEVotingSepolia>;
    getContractAt(
      name: "ConfidentialVoting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ConfidentialVoting>;
    getContractAt(
      name: "SimpleVoting",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SimpleVoting>;

    deployContract(
      name: "EthereumConfig",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EthereumConfig>;
    deployContract(
      name: "SepoliaConfig",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SepoliaConfig>;
    deployContract(
      name: "FHE",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHE>;
    deployContract(
      name: "IDecryptionOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDecryptionOracle>;
    deployContract(
      name: "IKMSVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IKMSVerifier>;
    deployContract(
      name: "IACL",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IACL>;
    deployContract(
      name: "IFHEVMExecutor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFHEVMExecutor>;
    deployContract(
      name: "IInputVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInputVerifier>;
    deployContract(
      name: "FHECounter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHECounter>;
    deployContract(
      name: "FHEVoting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVoting>;
    deployContract(
      name: "FHEVotingLocal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVotingLocal>;
    deployContract(
      name: "FHEVotingMinimal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVotingMinimal>;
    deployContract(
      name: "FHEVotingMock",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVotingMock>;
    deployContract(
      name: "FHEVotingSepolia",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVotingSepolia>;
    deployContract(
      name: "ConfidentialVoting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ConfidentialVoting>;
    deployContract(
      name: "SimpleVoting",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimpleVoting>;

    deployContract(
      name: "EthereumConfig",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EthereumConfig>;
    deployContract(
      name: "SepoliaConfig",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SepoliaConfig>;
    deployContract(
      name: "FHE",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHE>;
    deployContract(
      name: "IDecryptionOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDecryptionOracle>;
    deployContract(
      name: "IKMSVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IKMSVerifier>;
    deployContract(
      name: "IACL",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IACL>;
    deployContract(
      name: "IFHEVMExecutor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFHEVMExecutor>;
    deployContract(
      name: "IInputVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInputVerifier>;
    deployContract(
      name: "FHECounter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHECounter>;
    deployContract(
      name: "FHEVoting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVoting>;
    deployContract(
      name: "FHEVotingLocal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVotingLocal>;
    deployContract(
      name: "FHEVotingMinimal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVotingMinimal>;
    deployContract(
      name: "FHEVotingMock",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVotingMock>;
    deployContract(
      name: "FHEVotingSepolia",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEVotingSepolia>;
    deployContract(
      name: "ConfidentialVoting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ConfidentialVoting>;
    deployContract(
      name: "SimpleVoting",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SimpleVoting>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
